services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: staff
    ports:
      - '3309:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
